### ISSUE TITLE
Question about the training iterations 

### ISSUE THREAD

**Issue by TicTacToePP** [DeepMed-Lab-ECNU/BCP#10]
It seems the pretraining stage of ACDC uses 30k instead of 10k, which is inconsistent with the paper. Does this difference affect the results?
https://github.com/DeepMed-Lab-ECNU/BCP/blob/dc0685244aaed4302e680524fb3409aa8a534e37/code/ACDC_BCP_train.py#L193-L196

**Comment by byhwhite** [comment]
> It seems the pretraining stage of ACDC uses 30k instead of 10k, which is inconsistent with the paper. Does this difference affect the results?
> 
> https://github.com/DeepMed-Lab-ECNU/BCP/blob/dc0685244aaed4302e680524fb3409aa8a534e37/code/ACDC_BCP_train.py#L193-L196

Hi! Thanks for your patience!! We have checked the log files and made sure that we indeed pre-trained ACDC with 10,000 samples, just like in the paper. This was a negligence on our part in organizing the code, rather than an error in the experimental setup. Thank you again for bringing it to our attention! We will make the necessary modifications.

**Comment by TicTacToePP** [comment]
Got it, thanks!
